### ISSUE TITLE
EndorserCall error! Response is: rpc error: code = Unimplemented desc = unknown service pb.xendorser

### ISSUE THREAD

**Issue by chaunsin** [xuperchain/xuper-sdk-go#48]
请教一下,我现在操作3.7版本的链需要支持,调用合约,安装合约等操作都会出现以下类似的错误,请问怎么解决呢？

出现的错误:
```
2022/02/18 17:40:48 GetConfig: &{************:37101 {false false 400 aB2hpHnTBDxko3UoP2BpBZRujwhdcAFoT jknGxa6eyum1JrATWvSJKW3thJ9GKHA9n} 100 xchain}
2022/02/18 17:40:48 PreExecWithSelecUTXO EndorserCall failed, err: rpc error: code = Unimplemented desc = unknown service pb.xendorser
2022/02/18 17:40:48 DeployWasmContract preExe failed, err: EndorserCall error! Response is: rpc error: code = Unimplemented desc = unknown service pb.xendorser
panic: EndorserCall error! Response is: rpc error: code = Unimplemented desc = unknown service pb.xendorser
```

另外我的skd配置内容如下,也没有配置xendorser开关什么的
```yaml
endorseServiceHost: "*************"

complianceCheck:
  # 是否需要进行合规性背书
  isNeedComplianceCheck: false
  # 是否需要支付合规性背书费用
  isNeedComplianceCheckFee: false
  # 合规性背书费用
  complianceCheckEndorseServiceFee: 400
  # 支付合规性背书费用的收款地址
  complianceCheckEndorseServiceFeeAddr: aB2hpHnTBDxko3UoP2BpBZRujwhdcAFoT
  # 如果通过合规性检查，签发认证签名的地址
  complianceCheckEndorseServiceAddr: jknGxa6eyum1JrATWvSJKW3thJ9GKHA9n
#创建平行链所需要的最低费用
minNewChainAmount: "100"

# sdk调用生成账号相关的密码类型.简单来说生成的是否是国密算法。
crypto: "xchain"
txVersion: 1
```

我链的配置如下 `xchain.yaml`内容如下
```yaml
# node config
# 日志配置
log:
  # 模块名称
  module: xchain
  # 日志目录
  filepath: logs
  # 日志文件名
  filename: xchain
  fmt: logfmt
  # 是否打印命令行工具端口
  console: true
  # 日志等级
  level: debug

# RPC 服务暴露的端口
tcpServer:
  port: :37101
  # prometheus监控指标端口, 为空的话就不启动
  metricPort: :37200
  tls: false
  #cachePeriod: 2
  # 最大接受数据包长度

# 区块链节点配置
p2p:
  # module is the name of p2p module plugin, value is [p2pv2/p2pv1], default is p2pv2
  module: p2pv2
  port: 47101
  #certPath: ./data/tls/1
  #serviceName: saas_test.server.com
  #bootNodes:
  #  - "/ip4/<ip>/tcp/<port>/p2p/<node_hash>" for p2pv2 or - "<ip>:<port>" for p2pv1
  #staticNodes:
  #  xuper:
  #    - "127.0.0.1:47102"

miner:
  # 密钥存储路径
  keypath: ./data/keys

# 数据存储路径
datapath: ./data/blockchain

# 多盘存储的路径
#datapathOthers:
#    - /ssd1/blockchain
#    - /ssd2/blockchain
#    - /ssd3/blockchain

utxo:
  # utxo的内存LRUCache大小，表示内存中最多缓存多少个UtxoItem
  cachesize: 2000000
  # GenerateTx的临时锁定期限，默认是60秒
  tmplockSeconds: 60
  #单个块的合约执行的总时间(单位ms)
  contractExecutionTime: 500

kernel:
  # minNewChainAmount 设置创建平行链时最少要转多少钱到同链名address
  minNewChainAmount: "100"
  newChainWhiteList:
    - dpzuVdosQrF2kmzumhVeFQZa1aYcdgFpN: true

# 管理native合约的配置
native:
  enable: false
  # 与部署相关的配置
  deploy:
    # 部署白名单，列表为钱包地址
    whiteList:
      enable: false
      addresses:
        - dpzuVdosQrF2kmzumhVeFQZa1aYcdgFpN

  # docker相关配置
  docker:
    enable: false
    # 合约运行的镜像名字
    imageName: "docker.io/centos:7.5.1804"
    # cpu核数限制，可以为小数
    cpus: 1
    # 内存大小限制
    memory: "1G"

  # 停止合约的等待秒数，超时强制杀死
  stopTimeout: 3

# 插件配置文件路径
pluginConfPath: "./conf/plugins.conf"

# 是否启用p2p核心节点直连
coreConnection: false

txidCacheExpiredTime: "10s"

# 是否压缩交易/区块
enableCompress: true

# 块广播模式
blockBroadcaseMode: 0

# 剪枝配置
prune:
  switch: false
  bcname: "xuper"
  targetBlockid: "xxx"

# wasm合约配置

wasm:
  driver: "xvm"
  enableUpgrade: false
  xvm:
    optLevel: 0

# 是否开启默认的XEndorser背书服务
enableXEndorser: false
```
我是用v2和v1.1版本的sdk都不行,恳求帮助
